
before:
  hooks:
    - go mod tidy
    - make testshort

builds:
- id: kubecolor
  main: ./main.go
  binary: kubecolor
  env:
    - CGO_ENABLED=0
  ldflags:
    - -s -w
    - -X main.Version={{.Version}}
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - arm64
    - amd64
    - ppc64le

archives:
- builds:
  - kubecolor
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip

brews:
- name: kubecolor
  repository:
    owner: kubecolor
    name: homebrew-tap
    token: "{{ .Env.GLOBAL_GITHUB_TOKEN }}"
  homepage: "https://github.com/kubecolor/kubecolor"
  description: "Colorize your kubectl output"
  license: "MIT"
  folder: Formula
  install: |
    bin.install "kubecolor"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
