apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  annotations:
    foo: bar
  labels:
    test: test
  name: no-image-pods
  namespace: kubecolor
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: no-image-pods
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: no-image-pods
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - no-image-pods
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - command:
        - sleep 
        - 5m
        image: alpine:none
        imagePullPolicy: IfNotPresent
        name: sleep
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 70Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      securityContext: {}
